spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/dataclean?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    hikari:
      username: root
      password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB

logging:
  level:
    com.liaoin.dataclean: trace

swagger:
  enabled: true
  title: 数据清洗
  base-package: com.liaoin.dataclean.controller